### ISSUE TITLE
А можно еще добавить в первый урок ?

### ISSUE THREAD

**Issue by sea5kg** [neosfun/neosfun.github.io#7]
write <user> pts/1

**Comment by sea5kg** [comment]
посмотреть список кто подключен
who
Типа вывести красным цветом
echo -e "\e[41m \r\n\r\n\r\n \e[4m Who are you ? \r\n\r\n\r\n\e[0m" > /dev/pts/0

**Comment by Daniil159x** [comment]
Fixed 71de98a60b861c8e11cee74b194e02a98b0ae61d
